//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.SubComments = new HashSet<SubComment>();
        }
    
        public int CId { get; set; }
        public Nullable<int> CUId { get; set; }
        public Nullable<int> CFId { get; set; }
        public string CText { get; set; }
        public Nullable<bool> CStatus { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubComment> SubComments { get; set; }
    }
}
