//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int CId { get; set; }
        public Nullable<int> CUId { get; set; }
        public string CText { get; set; }
        public Nullable<int> CFId { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<bool> CStatus { get; set; }
    }
}
