//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crews
    {
        public int CId { get; set; }
        public string CName { get; set; }
        public Nullable<System.DateTime> CBirthday { get; set; }
        public string CPicture { get; set; }
        public string CLife { get; set; }
    }
}
