//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmCrew
    {
        public int FCId { get; set; }
        public Nullable<int> FId { get; set; }
        public Nullable<int> CId { get; set; }
        public string FCMission { get; set; }
    
        public virtual Crews Crews { get; set; }
        public virtual Films Films { get; set; }
    }
}
