//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int LId { get; set; }
        public Nullable<int> LUId { get; set; }
        public Nullable<int> LFId { get; set; }
        public Nullable<int> LType { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Users Users { get; set; }
    }
}
