//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmPortaliEntities : DbContext
    {
        public FilmPortaliEntities()
            : base("name=FilmPortaliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Crews> Crews { get; set; }
        public virtual DbSet<FilmCategory> FilmCategory { get; set; }
        public virtual DbSet<FilmCrew> FilmCrew { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Sources> Sources { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<SubComments> SubComments { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Views> Views { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
