//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sources
    {
        public int SId { get; set; }
        public Nullable<int> SFId { get; set; }
        public string SName { get; set; }
        public string SUrl { get; set; }
        public bool SStatus { get; set; }
    
        public virtual Films Films { get; set; }
    }
}
