//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Comments = new HashSet<Comments>();
            this.List = new HashSet<List>();
            this.SubComments = new HashSet<SubComments>();
            this.Views = new HashSet<Views>();
        }
    
        public int UId { get; set; }
        [StringLength(15, MinimumLength = 3, ErrorMessage = "Nick 3 ile 15 karakter arasında olmalıdır.")]
        [Required(ErrorMessage = "Bu Alan Boş Bırakılamaz")]
        public string UNick { get; set; }
        [Required(ErrorMessage = "Bu Alan Boş Bırakılamaz")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Geçerli mail adresi giriniz.")]
        public string UMail { get; set; }
        [Required(ErrorMessage = "Bu Alan Boş Bırakılamaz")]
        [DataType(DataType.Password)]
        [StringLength(80, MinimumLength = 6, ErrorMessage = "Şifreniz En az 6 karakter olmalıdır")]
        public string UPasswd { get; set; }
        [Compare(nameof(UPasswd),ErrorMessage = "Şifreler Eşleşmiyor")]
        public string UNPasswd { get; set; }
        [StringLength(12, MinimumLength = 3, ErrorMessage = "İsminiz 6 ile 12 karakter arasında olmalıdır.")]
        public string UName { get; set; }
        [StringLength(12, MinimumLength = 3, ErrorMessage = "Soyisminiz 6 ile 12 karakter arasında olmalıdır.")]
        public string USurname { get; set; }
        public string UInfo { get; set; }
        public string UImage { get; set; }
        public Nullable<System.DateTime> UBirthDate { get; set; }
        public Nullable<bool> UGender { get; set; }
        public string UTwitter { get; set; }
        public string UInstagram { get; set; }
        public bool UAppear { get; set; }
        public bool UNews { get; set; }
        public Nullable<System.DateTime> ULastSession { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<bool> UStatus { get; set; }
        public string URole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<List> List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubComments> SubComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Views> Views { get; set; }
    }
}
