//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UId { get; set; }
        public string UNick { get; set; }
        public string UMail { get; set; }
        public string UPasswd { get; set; }
        public string UName { get; set; }
        public string USurname { get; set; }
        public string UInfo { get; set; }
        public string UImage { get; set; }
        public Nullable<System.DateTime> UBirthDate { get; set; }
        public Nullable<bool> UGender { get; set; }
        public string UTwitter { get; set; }
        public string UInstagram { get; set; }
        public Nullable<bool> UAppear { get; set; }
        public Nullable<bool> UNews { get; set; }
        public Nullable<System.DateTime> UDate { get; set; }
        public Nullable<bool> UStatus { get; set; }
        public string URole { get; set; }
    }
}
