//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPortalı.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int VId { get; set; }
        public Nullable<int> VFId { get; set; }
        public Nullable<int> VUId { get; set; }
        public Nullable<System.DateTime> VDate { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual User User { get; set; }
    }
}
